### ISSUE TITLE
looks issue came back again. Not sure the reason , I used same command which is earlier was successful.

### ISSUE THREAD

**Issue by nraju-c** [captbrando/pgMail#10]
looks issue came back again. Not sure the reason , I used same command which is earlier was successful.

SELECT public.pgmail(
'Donotreply@abc.com',
'test@abc.com',
'Test_Subject',
'Test_Body_Plain'
);

_Originally posted by @nraju-c in https://github.com/captbrando/pgMail/issues/9#issuecomment-781613002_

**Comment by captbrando** [comment]
hrm, is it working again? This sounds like an issue somewhere outside of pgMail.

**Comment by nraju-c** [comment]
I am able to send the mails but receivers getting without subject in subject line & not showing To Address on Address Line.
Also getting below body.

Is it something i need to change any server settings? please advise on the same.

**Command** 
SELECT public.pgmail(
'Donotreply@abc.com',
'test@abc.com',
'Test_Subject',
'Test_Body_Plain'
);

**Mail Body**

XXXXX Thu, 21 Feb 2021 15:13:32 +0000
From: Donotreply@abc.com
To: testa@abc.com
Subject: Test_Subject
MIME-Version: 1.0
Content-type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

Test_Body_Plain.

**Comment by captbrando** [comment]
What mail server are you sending through?

**Comment by nraju-c** [comment]
i am using our corporate mail server **mail.abc.com**

**Comment by captbrando** [comment]
Hrm, I'd like to get some more info from you on this one. I'd like to move to a different medium. Can you let me know where I can email you and I'll send a quick note and then delete this issue?
