### ISSUE TITLE
tested pg_mail query ok but no mail got

### ISSUE THREAD

**Issue by Wangyegithubv** [captbrando/pgMail#11]
Sir ,i met a problem of pgmail.

there i installed finished and then had a test about send mail.
SELECT public.pgmail(
'victor_y_wang@wistron.com',
'victor_y_wang@wistron.com',
'Test_Subject',
'Test_Body_Plain'
);
above execute ok,but i cannot got the tested mail.

could you help me? @captbrando 
Tks Sir!!!

**Comment by captbrando** [comment]
Good morning. Can you check your connection to the mail server? When you install the function, you need to set up your mail server there. Your database server must be able to establish a TCP connection to that mail server without SMTP authentication.

**Comment by Wangyegithubv** [comment]
Yes sir, all config  of the function i sure just is ok.telnet smtpserver:25 also ok.There are other linux mail shell test just is ok too.
but when i use the pg function in pgadmin,it shows query done and return 1,but i can not got mail.

**Comment by Wangyegithubv** [comment]
my pg is 12.7 and installed pltcl pltclu

**Comment by captbrando** [comment]
OK, can you check the mail server logs to make sure that it actually was fully accepted and processed?

**Comment by Wangyegithubv** [comment]
hello, Sir. mail server nerver got the send mail apply.
maybe the function execute successfully and return 1 but the tcl can not control pg server to send mail out to mail server?
![image](https://user-images.githubusercontent.com/51010405/126939141-8f2919ab-cba7-40c9-8e9d-5dcd4b8c9072.png)
can you help me add some debug in your function.
tks very much!

**Comment by captbrando** [comment]
Can you show me your pgMail function where you replaced your mail server and port?

**Comment by Wangyegithubv** [comment]
sir ,my function as follow,tks your reply so quickly very much !
-- FUNCTION: public.pgmail(text, text, text, text, text)

-- DROP FUNCTION public.pgmail(text, text, text, text, text);

CREATE OR REPLACE FUNCTION public.pgmail(
	text,
	text,
	text,
	text,
	text DEFAULT ''::text)
    RETURNS integer
    LANGUAGE 'pltclu'
    COST 100
    VOLATILE PARALLEL UNSAFE
AS $BODY$
set mailfrom $1
set mailto $2
set mailsubject $3
set mailmessage $4
set mailmessage_html $5
if {$mailmessage ne "" && $mailmessage_html ne ""} {
	set multipart true
} else {
	set multipart false
}
set myHost "company outlook mail server"
set myPort 25
set mySock [socket $myHost $myPort]
set toemailaddress_start [string first "<" $mailto]
if {$toemailaddress_start != -1} {
	set toemailaddress_finish [string first ">" $mailto]
	set toemailaddress_start [expr $toemailaddress_start + 1]
	set toemailaddress_finish [expr $toemailaddress_finish - 1]
	set toemailaddress [string range $mailto $toemailaddress_start $toemailaddress_finish]
} else {
	set toemailaddress $mailto
}
set fromemailaddress_start [string first "<" $mailfrom]
if {$fromemailaddress_start != -1} {
	set fromemailaddress_finish [string first ">" $mailfrom]
	set fromemailaddress_start [expr $fromemailaddress_start + 1]
	set fromemailaddress_finish [expr $fromemailaddress_finish - 1]
	set fromemailaddress [string range $mailfrom $fromemailaddress_start $fromemailaddress_finish]
} else {
	set fromemailaddress $mailfrom
}
fileevent $mySock writable [list svcHandler $mySock]
fconfigure $mySock -buffering line
puts $mySock "HELO <ENTER YOUR DATABASESERVER HERE>"
gets $mySock name
puts $mySock "MAIL FROM: $fromemailaddress"
gets $mySock name
puts $mySock "RCPT TO: $toemailaddress"
gets $mySock name
puts $mySock "DATA"
gets $mySock name
puts $mySock "Date: [clock format [clock seconds] -format {%a, %d %b %Y %H:%M:%S +0000} -gmt true]"
puts $mySock "From: $mailfrom"
puts $mySock "To: $mailto"
puts $mySock "Subject: $mailsubject"
puts $mySock "MIME-Version: 1.0"
if {$multipart} {
	puts $mySock {Content-type: multipart/mixed; boundary="just_a_simple_boundary"}
}
if {$mailmessage ne ""} {
	if {$multipart} {puts $mySock "--just_a_simple_boundary"}
	puts $mySock "Content-type: text/plain; charset=UTF-8"
	puts $mySock "Content-Transfer-Encoding: 8bit"
	puts $mySock ""
	puts $mySock "$mailmessage"
}
if {$mailmessage_html ne ""} {
	if {$multipart} {puts $mySock "--just_a_simple_boundary"}
	puts $mySock "Content-type: text/html; charset=UTF-8"
	puts $mySock "Content-Transfer-Encoding: 8bit"
	puts $mySock ""
	puts $mySock "$mailmessage_html"
}
if {$multipart} {puts $mySock "--just_a_simple_boundary--"}
puts $mySock ""
puts $mySock "."
gets $mySock name
puts $mySock "QUIT"
gets $mySock name
close $mySock
return 1
$BODY$;

ALTER FUNCTION public.pgmail(text, text, text, text, text)
    OWNER TO postgres;

**Comment by captbrando** [comment]
This line:

`set myHost "company outlook mail server"`

You need to put the IP address or hostname of your mail server there.

**Comment by Wangyegithubv** [comment]
sir ,i just set myhost to 10.66.222.50 or fqdn，just execute function ok return 1.
but there no mail to my outlook mail server

**Comment by captbrando** [comment]
Do the logs on the server show the connection? If you dropped and replaced the function with the new server definition, and you have verified connection to the server, I would look at the mail server logs to make sure you don’t have an SMTP Auth issue.
