### ISSUE TITLE
Add encoding

### ISSUE THREAD

**Issue by GSN1970** [captbrando/pgMail#13]
Hi, Brandon!
I modify you pgMail, viz. add parameter -encoding utf-8 to 'fconfigure $mySock -buffering line' command. Without this a latin characters show as question sign.
Best regard, Glukhov Sergey.

**Comment by captbrando** [comment]
Hey there Glukhov! That's a great catch. I will work to get that added in today.

**Comment by captbrando** [comment]
Fixed with commit 17cedc812011b6c4e8cd79b26d71f74c0da2d11d
