### ISSUE TITLE
500: Internal Server Error 

### ISSUE THREAD

**Issue by tranicus** [captbrando/pgMail#7]
Hello Capt,

Getting internal server error from both chrome and Windows IE when tied to download tar.gz file.

**Comment by captbrando** [comment]
Where are you downloading this? I am unclear on where the actual issue is (i.e., if there is a problem with Github).

**Comment by tranicus** [comment]
Am I in the wrong link?

https://github.com/captbrando/pgMail/releases


Should I be download from the link below?

https://github.com/captbrando/pgMail

**Comment by captbrando** [comment]
That is the correct URL. I just downloaded it.
