### ISSUE TITLE
Subject & To address receiving as blank on mails

### ISSUE THREAD

**Issue by nraju-c** [captbrando/pgMail#9]
Hi,

I am successfully setup the pgMail but Subject & To address showing as blank on emails.
can you please advise what changes required on the code.

Thanks

**Comment by captbrando** [comment]
What happened when you reached this step of the readme?

*********

Once you have installed the stored function, simply call the 
procedure as follows.

select pgmail('Send From <from@from.com>','Send To <to@to.com>',
 'Subject goes here','Plaintext message body here.');

**Comment by nraju-c** [comment]
i am able to send mails but who ever receiving the mail without subject in subject line.
Also not showing To Address on Address Line.

But body receiving all the details.

XXXXX Thu, 17 Feb 2021 15:13:32 +0000
From: Donotreply@abc.com
To: testa@abc.com
Subject: Test_Subject
MIME-Version: 1.0
Content-type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

Test_Body_Plain.

**Comment by captbrando** [comment]
Can you share the command you are running to generate the email? This is not a problem I have ever seen before. Also which email client is being used on the receiving side?

**Comment by nraju-c** [comment]
below is the command i am using.

SELECT public.pgmail(
	'Donotreply@abc.com', 
	'test@abc.com', 
	'Test_Subject', 
	'Test_Body_Plain',
	''
);

**Comment by captbrando** [comment]
That should work fine. What email client is missing the subject?

**Comment by nraju-c** [comment]
Microsoft Outlook & it's on corporate mail domain.

**Comment by captbrando** [comment]
I have never seen that happen. Can you do me a favor and remove the last field (you have supplied it as empty) and see I that does anything different?

Also what mail server are you using? Have you tried sending a test to Gmail and seeing if that looks the same?

**Comment by nraju-c** [comment]
let me try on gmail

**Comment by nraju-c** [comment]
looks it worked with below.

SELECT public.pgmail(
'Donotreply@abc.com',
'test@abc.com',
'Test_Subject',
'Test_Body_Plain'
);

**Comment by nraju-c** [comment]
How to add multiple To email addresses on pgmail?
Looks below not working.

SELECT public.pgmail(
'Donotreply@abc.com',
'test@abc.com,test2@abc.com,test3@abc.com,test4@abc.com',
'Test_Subject',
'Test_Body_Plain'
);

**Comment by captbrando** [comment]
You don't want to use multiple addresses. You should make the call to pgMail individually for each email address.

**Comment by nraju-c** [comment]
ok. Thanks

**Comment by nraju-c** [comment]
looks issue came back again. Not sure the reason , I used same command which is earlier was successful.


SELECT public.pgmail(
'Donotreply@abc.com',
'test@abc.com',
'Test_Subject',
'Test_Body_Plain'
);
